# Generated by Django 5.2.6 on 2025-09-08 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('sleep', 'Sleep'), ('pain', 'Pain'), ('focus', 'Focus'), ('creativity', 'Creativity'), ('relaxation', 'Relaxation'), ('energy', 'Energy')], max_length=16)),
                ('experience_level', models.CharField(choices=[('new', 'New'), ('casual', 'Casual'), ('regular', 'Regular'), ('heavy', 'Heavy')], max_length=16)),
                ('tolerance', models.PositiveSmallIntegerField(help_text='0 = very low, 10 = very high', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('anytime', 'Anytime')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
